version: '3'

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    # ports:
    #   - 3000:3000
    expose:
      - 3000
    networks:
      - my-network

networks:
  my-network:
    external: true
